name: Create iCal

on:
  push:
  workflow_dispatch:

jobs:
  ical:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.0

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create ical file
        run: python app.py

      - name: Upload ics File
        uses: actions/upload-artifact@v3
        with:
          name: 'calendar.ics'
          path: 'calendar.ics'

      - name: Save ics file
        run: |
          ls
          git status
          echo "Pull latest changes"
          git pull
          pwd
          git config --global user.email "dtu.amit@gmail.com"
          git config --global user.name "Amit Kumar [Bot]"
          git add .
          git commit -m "Save ical file"

      - name: Push changes
        uses: ad-m/github-push-action@master
